version: 2
jobs:
  build:
    docker:
      - image: "python:3.6"
    steps:
      - checkout
      - run: apt update
      - run: apt install gettext-base
      - run: envsubst < setup.py > setup.py
      - run: pip install twine
      - run: python setup.py sdist bdist_wheel
      - run: ls -l
      - run: twine upload dist/*
    branches:
      only: master
